### PR TITLE
Feature/switch

### PR DESCRIPTION
**Pull request by yakuphanbilgic**
#22 Switch component added. Would appreciate any feedback.

### CODE REVIEW

**Comment by ergenekonyigit** [comment]
First of all, thank you for your contribution and effort. We reviewed your PR.

We could not direct you correctly because the requirements are missing in the ADR. Your PR got us moving. 
We updated the Label system and defined the Switch ADR. You can access the current ADR [here](https://github.com/Trendyol/baklava-react-native/issues/22).

**Comment by yakuphanbilgic** [comment]
You are welcome! 

Would you consider my pull request if I modify my implementation so that it satisfy the ADR or would you rather continue with your own development?

**Comment by ergenekonyigit** [comment]
Yes, if you can change your pr with the requested adr rules and props we can merge your contribution. Just one thing to remember, we want to exact the same UI on both os, so maybe you should implement a switch without a react native switch component.

**Comment by yakuphanbilgic** [comment]
Thanks for the feedback! I'll look into it and reopen my pull request after everything satisfies the requested ADRs.

**Comment by ergenekonyigit** [comment]
Hi, thank you for your work, it looks great. I have just updated some size and text issues. Can you update screenshots with these images, then we can merge this pr. 💯 

switch
switch-custom
switch-disabled

switch-label

**Comment by yakuphanbilgic** [comment]
Great to hear! I have changed the screenshots with the ones you sent ✅

**Pull request merged**
